# Configuration file for running the ACASXu benchmark (all properties).
general:
  # root_path: /projects/air/vnncomp2024-benchmarks/benchmarks/acasxu_2023  # Alexandros Path
  # root_path: ../../../vnncomp2024_benchmarks/benchmarks/acasxu_2023  # Zahra's Path
  root_path: ../vnncomp2024_benchmarks/benchmarks/acasxu_2023  # Max's Path

  csv_name: instances.csv
  enable_incomplete_verification: False
  device: cpu
  seed: 0

solver:
  batch_size: 1 
  beta-crown:
    iteration: 20
bab:
  branching:
    method: RL
    rl:
      experiment: "acas"   #---change   
      eval: False
      # extras: []
      extras:
        - thresholds
      logging:
        file: null
        color: True
        debug: False
      pnet:
        gH: 64
        tH: 128
        nheads: 4
        nlayers: 2
        GAT: True
        useDynamicGraph: True
        bidirectional: False
      training:
        buffer: "buffer.pkl"
        policynet: "policy-checkpoint.pt"
        targetnet: "target-checkpoint.pt"
        batchSize: 32                     
        loop: 8
        totalEpochs: 1   
        updatePolicyFrequency: 5
        updateTargetFrequency: 5
        gamma: 0.99
        lr: 0.001
        datasetShuffle: True
        TargetedData: safe
        splitRatio: 0.8
        maxInstances: 1   #---change
        trainingMode: imitation #---change     # Training mode: 'imitation' for expert-only, 'qlearn' for RL-only, 'full' for both."
        reward:
          norm: null
          bonus: 10.0
          penalty: -1.0
      egreedy:
        enabled: False
        epsilon: 1
        epsilonDecay: 0.99
        minEpsilon: 0.1
        ePath: "epsilon.pt"
      expert:
        enabled: True
        useExpertUntilEpisode: 1
        learnToImitateExpertEpochs: 100      #---change
  timeout: 300
  max_iterations: 400        #---change

attack:
  pgd_order: after
  pgd_restarts: 10000
  pgd_restart_when_stuck: True

# attack:
#   pgd_order: skip