# Configuration file for running the ACASXu benchmark (all properties).
general:
  root_path: ../vnncomp2024_benchmarks/benchmarks/acasxu_2023
  csv_name: instances.csv
  enable_incomplete_verification: False
  dataset_output_dir: /cluster/home/sur/mp773/proj/bright/dl-verifier/input-splitting/dataset
solver:
  batch_size: 1
  beta-crown:
    iteration: 20
bab:
  branching:
    method: generate_dataset
  timeout: 300
attack:
  pgd_order: after
  pgd_restarts: 10000
  pgd_restart_when_stuck: True
