dataset:
  type: "imagenet_vggnet16"          
  root: "benchmarks/vggnet16_benchmark2022/imagenet-sample"

  # still keep these for grid mode
  grid_size: 6
  iou_threshold: 0.8
  score_threshold: 0.0
  max_segments: 5

segmentation:
  model_name: "facebook/sam2-hiera-large"
  device: "auto"        # "auto", "cpu" or "cuda"
  prompt_mode: "grid"     # "grid" or "manual"
  prompts_path: "benchmarks/points/"

  grid_size: 6
  iou_threshold: 0.8
  score_threshold: 0.0
  max_segments: 1

  vis: True  

verification:
  epsilon: [0.0001] 
  dilation_radius: 0
  num_classes: 1000

  perturb_pixels: [50176]
  perturb_select: "random"
  perturb_seed: 0

onnx:
  source_model: "benchmarks/vggnet16_benchmark2022/onnx/vgg16-7.onnx"
  target_name: "vgg16-7.onnx"

output:
  benchmark_dir: "benchmarks/vggnet16_benchmark2022_segmented_one_img_k/"
  timeout: 1200

run:
  # Option 1: process images by index (sorted over all sample images)
  indices: [63]    # Indices of images to process (0-based)

  # Option 2: explicit paths (leave empty if using indices)
  # image_paths: ["benchmarks/vggnet16_benchmark2022/imagenet-sample"]
  # Directory will be expanded to image files by pipeline.py
