dataset:
  type: "cifar100"          
  root: "benchmarks/cifar100_2024/decoded_vnnlibs"

segmentation:
  model_name: "facebook/sam2-hiera-large"
  device: "auto"        # "auto", "cpu" or "cuda"
  prompt_mode: "grid"     # "grid" or "manual"
  prompts_path: "benchmarks/points/"

  grid_size: 6
  iou_threshold: 0.8
  score_threshold: 0.0
  max_segments: 1

  vis: True

  dilation_radius: 2

verification:
  epsilon: [0.0039] 

  num_classes: 100

  perturb_pixels: [1024]
  perturb_select: "random"
  perturb_seed: 0

onnx:
  source_model: "benchmarks/cifar100_2024/onnx"
  target_name: ["CIFAR100_resnet_large.onnx", "CIFAR100_resnet_medium.onnx"]

output:
  benchmark_dir: "benchmarks/cifar100_all_d_2/"
  timeout: 100

run:
  # Option 1: process images by index (sorted over all sample images)
  # indices: []    # Indices of images to process (0-based)

  image_paths: ["benchmarks/cifar100_2024/decoded_vnnlibs"]

