general:
  enable_incomplete_verification: False
  dataset_output_dir: /cluster/home/sur/mp773/proj/bright/dl-verifier/oval21_betacrown/dataset
solver:
  batch_size: 1
  beta-crown:
    iteration: 20
bab:
  timeout: 3600
  branching:
    method: generate_dataset
    reduceop: min
    candidates: 1
attack:
  pgd_order: middle
